# Generated by Django 6.0.3 on 2026-04-04 04:22

import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import fasos.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Sistem',
                'verbose_name_plural': 'Manajemen User',
                'ordering': ['username'],
            },
            managers=[
                ('objects', fasos.managers.SoftDeleteUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BatasKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kecamatan', models.CharField(max_length=150)),
                ('kd_kcmtan', models.CharField(max_length=20, unique=True)),
                ('tipe', models.CharField(default='Kecamatan', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geojson_file', models.FileField(blank=True, help_text='Upload file .geojson (Format: FeatureCollection)', null=True, upload_to='geojson_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kecamatans', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'Batas Kecamatan',
                'verbose_name_plural': 'Data Spasial Kecamatan (DTRB)',
            },
        ),
        migrations.CreateModel(
            name='CCTVFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kode_cam', models.CharField(max_length=50)),
                ('nama_lokasi', models.TextField(max_length=150)),
                ('tipe', models.CharField(choices=[('Perangkat Keamanan Pemerintah Daerah - CCTV', 'Perangkat Keamanan Pemerintah Daerah- CCTV'), ('Perangkat Keamanan Instansi Vertikal - CCTV', 'Perangkat Keamanan Instansi Vertikal- CCTV')], default='Perangkat Keamanan Pemerintah Daerah - CCTV', max_length=50)),
                ('wilayah', models.CharField(choices=[('Polsek Balaraja', 'Polsek Balaraja'), ('Polsek Kresek', 'Polsek Kresek'), ('Polsek Mauk', 'Polsek Mauk'), ('Polsek Kronjo', 'Polsek Kronjo'), ('Polsek Pasar Kemis', 'Polsek Pasar Kemis'), ('Polsek Tigaraksa', 'Polsek Tigaraksa'), ('Polsek Panongan', 'Polsek Panongan'), ('Polsek Cikupa', 'Polsek Cikupa'), ('Polsek Cisoka', 'Polsek Cisoka'), ('Polresta Tangerang', 'Polresta Tangerang')], default='Polresta Tangerang', max_length=100)),
                ('sn_camera', models.CharField(max_length=100)),
                ('sn_modem', models.CharField(max_length=100)),
                ('tgl_pemasangan', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cctv_etle/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cctv_facilities', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'CCTV Monitoring',
                'verbose_name_plural': 'Data CCTV (Diskominfo)',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='DistrictOfficeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('tipe', models.CharField(choices=[('Perangkat Daerah', 'Perangkat Daerah'), ('Instansi Vertikal', 'Instansi Vertikal')], default='Perangkat Daerah', max_length=50)),
                ('alamat', models.TextField(max_length=255)),
                ('no_telp', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Perencanaan/Pengajuan', 'Perencanaan/Pengajuan'), ('Dalam Masa Peninjauan', 'Dalam Masa Peninjauan'), ('Perencanaan Dibatalkan', 'Perencanaan Dibatalkan'), ('Dalam Masa Pembangunan', 'Dalam Masa Pembangunan'), ('Pembangunan Selesai/Belum Beroperasi', 'Pembangunan Selesai/Belum Beroperasi'), ('Pembangunan Selesai/Sudah Beroperasi', 'Pembangunan Selesai/Sudah Beroperasi'), ('Tutup/Sudah Tidak Beroperasi', 'Tutup/Sudah Tidak Beroperasi')], default='Perencanaan/Pengajuan', max_length=50)),
                ('hari_beroperasi', models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], max_length=50)),
                ('jam_beroperasi', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='local_government_office/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_district_offices', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'Kantor Pemerintahan Daerah',
                'verbose_name_plural': 'Data Kantor Pemda (Setda)',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('koderumahsakit', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=150)),
                ('tipe', models.CharField(choices=[('Rumah Sakit', 'Rumah Sakit'), ('Puskesmas', 'Puskesmas'), ('Klinik', 'Klinik'), ('Apotik', 'Apotik')], default='Rumah Sakit', max_length=50)),
                ('jenis', models.CharField(choices=[('Rumah Sakit Umum', 'Rumah Sakit Umum'), ('Rumah Sakit Khusus', 'Rumah Sakit Khusus'), ('-', '-')], default='Rumah Sakit Umum', max_length=50)),
                ('tingkatan', models.CharField(choices=[('Kelas A', 'Kelas A'), ('Kelas B', 'Kelas B'), ('Kelas C', 'Kelas C'), ('Belum Mengisi Tingkatan', 'Belum Mengisi Tingkatan'), ('-', '-')], default='Belum Mengisi Tingkatan', max_length=50)),
                ('kepemilikan', models.CharField(choices=[('Dikelola Pemerintah', 'Dikelola Pemerintah'), ('Dikelola Swasta', 'Dikelola Swasta'), ('Dikelola Organisasi Sosial', 'Dikelola Organisasi Sosial'), ('Belum Mengisi Penyelenggara', 'Belum Mengisi Penyelenggara'), ('-', '-')], default='Belum Mengisi Penyelenggara', max_length=50)),
                ('alamat', models.TextField(max_length=255)),
                ('no_telp', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Perencanaan/Pengajuan', 'Perencanaan/Pengajuan'), ('Dalam Masa Peninjauan', 'Dalam Masa Peninjauan'), ('Perencanaan Dibatalkan', 'Perencanaan Dibatalkan'), ('Dalam Masa Pembangunan', 'Dalam Masa Pembangunan'), ('Pembangunan Selesai/Belum Beroperasi', 'Pembangunan Selesai/Belum Beroperasi'), ('Pembangunan Selesai/Sudah Beroperasi', 'Pembangunan Selesai/Sudah Beroperasi'), ('Tutup/Sudah Tidak Beroperasi', 'Tutup/Sudah Tidak Beroperasi')], default='Perencanaan/Pengajuan', max_length=50)),
                ('hari_beroperasi', models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Setiap Hari', max_length=50)),
                ('jam_beroperasi', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medical_facility/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_facilities', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'Fasilitas Kesehatan',
                'verbose_name_plural': 'Data Faskes (Dinkes)',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opds', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'Organisasi Perangkat Daerah',
                'verbose_name_plural': 'Master OPD',
                'ordering': ['kode'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='opd',
            field=models.ForeignKey(blank=True, db_column='opd_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='fasos.opd', to_field='uuid'),
        ),
    ]
