# Generated by Django 6.0.3 on 2026-04-03 10:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatasKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=150)),
                ('kd_kcmtan', models.CharField(max_length=20)),
                ('tipe', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Batas Kecamatan',
                'verbose_name_plural': 'Data Spasial Kecamatan',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'User Sistem', 'verbose_name_plural': 'Manajemen User'},
        ),
        migrations.AlterModelOptions(
            name='medicalfacility',
            options={'ordering': ['-date_field'], 'verbose_name': 'Fasilitas Kesehatan', 'verbose_name_plural': 'Data Faskes (Dinkes)'},
        ),
        migrations.AlterModelOptions(
            name='opd',
            options={'ordering': ['kode'], 'verbose_name': 'Organisasi Perangkat Daerah', 'verbose_name_plural': 'Master OPD'},
        ),
        migrations.RenameField(
            model_name='medicalfacility',
            old_name='updated_at',
            new_name='date_field',
        ),
        migrations.RemoveField(
            model_name='medicalfacility',
            name='created_at',
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='kepemilikan',
            field=models.CharField(choices=[('Dikelola Pemerintah', 'Dikelola Pemerintah'), ('Dikelola Swasta', 'Dikelola Swasta'), ('Dikelola Organisasi Sosial', 'Dikelola Organisasi Sosial'), ('Belum Mengisi Penyelenggara', 'Belum Mengisi Penyelenggara'), ('-', '-')], default='Belum Mengisi Penyelenggara', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='koderumahsakit',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='tipe',
            field=models.CharField(choices=[('Rumah Sakit', 'Rumah Sakit'), ('Puskesmas', 'Puskesmas'), ('Klinik', 'Klinik'), ('Apotik', 'Apotik')], default='Rumah Sakit', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='hari_beroperasi',
            field=models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Setiap Hari', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='jenis',
            field=models.CharField(choices=[('Rumah Sakit Umum', 'Rumah Sakit Umum'), ('Rumah Sakit Khusus', 'Rumah Sakit Khusus'), ('-', '-')], default='Rumah Sakit Umum', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='nama',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='tingkatan',
            field=models.CharField(choices=[('Kelas A', 'Kelas A'), ('Kelas B', 'Kelas B'), ('Kelas C', 'Kelas C'), ('Belum Mengisi Tingkatan', 'Belum Mengisi Tingkatan'), ('-', '-')], default='Belum Mengisi Tingkatan', max_length=50),
        ),
        migrations.CreateModel(
            name='CCTVFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_cam', models.CharField(max_length=50)),
                ('nama_lokasi', models.TextField(max_length=150)),
                ('tipe', models.CharField(choices=[('Perangkat Keamanan Pemerintah Daerah - CCTV', 'Perangkat Keamanan Pemerintah Daerah- CCTV'), ('Perangkat Keamanan Instansi Vertikal - CCTV', 'Perangkat Keamanan Instansi Vertikal- CCTV')], default='Perangkat Keamanan Pemerintah Daerah - CCTV', max_length=50)),
                ('wilayah', models.CharField(choices=[('Polsek Balaraja', 'Polsek Balaraja'), ('Polsek Kresek', 'Polsek Kresek'), ('Polsek Mauk', 'Polsek Mauk'), ('Polsek Kronjo', 'Polsek Kronjo'), ('Polsek Pasar Kemis', 'Polsek Pasar Kemis'), ('Polsek Tigaraksa', 'Polsek Tigaraksa'), ('Polsek Panongan', 'Polsek Panongan'), ('Polsek Cikupa', 'Polsek Cikupa'), ('Polsek Cisoka', 'Polsek Cisoka'), ('Polresta Tangerang', 'Polresta Tangerang')], default='Polresta Tangerang', max_length=100)),
                ('sn_camera', models.CharField(max_length=100)),
                ('sn_modem', models.CharField(max_length=100)),
                ('tgl_pemasangan', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cctv_etle/')),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CCTV Monitoring',
                'verbose_name_plural': 'Data CCTV (Diskominfo)',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='DistrictOfficeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('tipe', models.CharField(choices=[('Perangkat Daerah', 'Perangkat Daerah'), ('Instansi Vertikal', 'Instansi Vertikal')], default='Perangkat Daerah', max_length=50)),
                ('alamat', models.TextField(max_length=255)),
                ('no_telp', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Perencanaan/Pengajuan', 'Perencanaan/Pengajuan'), ('Dalam Masa Peninjauan', 'Dalam Masa Peninjauan'), ('Perencanaan Dibatalkan', 'Perencanaan Dibatalkan'), ('Dalam Masa Pembangunan', 'Dalam Masa Pembangunan'), ('Pembangunan Selesai/Belum Beroperasi', 'Pembangunan Selesai/Belum Beroperasi'), ('Pembangunan Selesai/Sudah Beroperasi', 'Pembangunan Selesai/Sudah Beroperasi'), ('Tutup/Sudah Tidak Beroperasi', 'Tutup/Sudah Tidak Beroperasi')], default='Perencanaan/Pengajuan', max_length=50)),
                ('hari_beroperasi', models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], max_length=50)),
                ('jam_beroperasi', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='local_government_office/')),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_offices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kantor Pemerintahan Daerah',
                'verbose_name_plural': 'Data Kantor Pemda (Setda)',
                'ordering': ['-date_field'],
            },
        ),
    ]
