# Generated by Django 6.0.3 on 2026-04-03 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasos', '0002_bataskecamatan_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bataskecamatan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
        migrations.AddField(
            model_name='cctvfacility',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
        migrations.AddField(
            model_name='districtofficefacility',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
    ]
