# Generated by Django 6.0.3 on 2026-04-03 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasos', '0003_bataskecamatan_uuid_cctvfacility_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
        migrations.AddField(
            model_name='opd',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Auto-generated unique identifier', unique=True),
        ),
    ]
